/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shiki (https://sketchfab.com/RyougiShiki)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lotus-flower-by-geometry-nodes-398b0f0eafe640a2a3dec98305a8e1c3
Title: Lotus Flower by Geometry Nodes
*/

import * as THREE from 'three'
import { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Flower_Material_0: THREE.Mesh
    Flower_Material_0_1: THREE.Mesh
    Flower_Material_0_2: THREE.Mesh
    Flower_Material_0_3: THREE.Mesh
    Flower_Material_0_4: THREE.Mesh
    Flower_Material_0_5: THREE.Mesh
    Flower_Material_0_6: THREE.Mesh
    Flower_Material_0_7: THREE.Mesh
    Flower_Material_0_8: THREE.Mesh
    Flower_Material_0_9: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshPhysicalMaterial
  }
}

const LOTUS_PATH = '/assets/lotus_flower_by_geometry_nodes/scene.gltf'

export function Lotus(props: JSX.IntrinsicElements['group']) {
  const groupRef = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF(LOTUS_PATH) as unknown as GLTFResult

  // Gentle rotation animation
  useFrame((state) => {
    if (groupRef.current) {
      groupRef.current.rotation.y = Math.sin(state.clock.elapsedTime * 0.3) * 0.1
      groupRef.current.position.y = Math.sin(state.clock.elapsedTime * 0.5) * 0.05
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Flower_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_1.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_2.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_3.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_4.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_5.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_6.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_7.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_8.geometry} material={materials.Material} />
          <mesh geometry={nodes.Flower_Material_0_9.geometry} material={materials.Material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(LOTUS_PATH)

export default Lotus
